### PR TITLE
(feature) working websocket boilerplate.

### PR DESCRIPTION
**Pull request by Janis-H**
**Problem**: Connecting websocket between frontend and backend
**Solution**: Added connection to index.jsx and server.js
**Notes**: 
* messages append to the page after sending
* might move connection position in the front-end

### CODE REVIEW

**Review by cvanspl1 — APPROVED** [review]
Changes approved.

**Review by amirmarcel — APPROVED** [review]

**Comment by amirmarcel** [comment]
looks good!!

**Review by mlndz-la — APPROVED** [review]
Approve 👍

**Review by mlndz-la — APPROVED** [review]

**Review by Janis-H — COMMENTED** [review]
Approved!

**Review by cvanspl1 — APPROVED** [review]
Changes approved.

**Review by mlndz-la — APPROVED** [review]

**Pull request merged**
